# Site settings
author: Rachel Beery
title: Rachel's Blog
header-img: img/home-bg.png
email: rachenicolebeery@gmail.com
copyright_name: Rachel Beery
description: > # this means to ignore newlines until "baseurl:"
  Flatiron Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rachelbeery

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
